import { db } from "../db";
import { produtos } from "@shared/schema";

// Cardápio completo com 100 pizzas organizadas por categorias

const cardapio = [
  // PEIXES (11 pizzas)
  {
    nome: "Atum",
    descricao: "Atum desfiado combinado com cebola, trazendo sabor marcante e levemente salgado",
    preco: "45.90",
    categoria: "Peixes",
    ingredientesTexto: "Atum, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Atum Cheese",
    descricao: "Atum com mussarela derretida, equilibrando intensidade e cremosidade",
    preco: "47.90",
    categoria: "Peixes",
    ingredientesTexto: "Atum, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Atum Cebola",
    descricao: "Atum temperado com cebola refogada, sabor clássico e aromático",
    preco: "46.90",
    categoria: "Peixes",
    ingredientesTexto: "Atum, cebola refogada, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Atum Muss",
    descricao: "Atum com mussarela, textura macia e sabor suave",
    preco: "45.90",
    categoria: "Peixes",
    ingredientesTexto: "Atum, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Atum UVA",
    descricao: "Atum com uva passa, contraste agridoce sofisticado",
    preco: "42.90",
    categoria: "Peixes",
    ingredientesTexto: "Atum, uva passa, mussarela",
    tipoPizza: "doce",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Espanhola",
    descricao: "Atum, champignon, azeitona, bacon, cebola, mussarela e tomate – pizza rica e complexa",
    preco: "52.90",
    categoria: "Peixes",
    ingredientesTexto: "Atum, champignon, azeitona, bacon, cebola, mussarela, tomate, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 22,
  },
  {
    nome: "Parma",
    descricao: "Atum, presunto de Parma, champignon, cebola e mussarela – sabor intenso e refinado",
    preco: "58.90",
    categoria: "Peixes",
    ingredientesTexto: "Atum, presunto de Parma, champignon, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Romana",
    descricao: "Mussarela, alho, cebola e tomate – simples e aromática",
    preco: "41.90",
    categoria: "Peixes",
    ingredientesTexto: "Mussarela, alho, cebola, tomate, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 16,
  },
  {
    nome: "Camarão",
    descricao: "Camarão refogado com mussarela – sabor marítimo marcante",
    preco: "62.90",
    categoria: "Peixes",
    ingredientesTexto: "Camarão, mussarela, alho, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Bacalhau",
    descricao: "Bacalhau desfiado com legumes e mussarela – tradicional e encorpada",
    preco: "64.90",
    categoria: "Peixes",
    ingredientesTexto: "Bacalhau, cebola, pimentão, azeitona, batata, mussarela",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 22,
  },
  {
    nome: "Alliche",
    descricao: "Aliche, parmesão e tomate – salgada e intensa",
    preco: "48.90",
    categoria: "Peixes",
    ingredientesTexto: "Aliche, parmesão, tomate, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },

  // CALABRESA (10 pizzas)
  {
    nome: "Calabresa",
    descricao: "Calabresa fatiada com cebola",
    preco: "42.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Baiana",
    descricao: "Calabresa, mussarela e pimenta – levemente picante",
    preco: "44.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, mussarela, pimenta, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Creta",
    descricao: "Calabresa, escarola, milho, ovo, cebola, tomate e mussarela – completa e rústica",
    preco: "49.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, escarola, milho, ovo, cebola, tomate, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 21,
  },
  {
    nome: "Calabria",
    descricao: "Calabresa, brócolis, milho, cebola e alho – sabor forte e aromático",
    preco: "47.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, brócolis, milho, cebola, alho, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Di-A-Dia",
    descricao: "Calabresa, tomate, parmesão e manjericão – clássica e equilibrada",
    preco: "43.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, tomate, parmesão, manjericão, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Pantanal",
    descricao: "Calabresa, champignon, palmito, milho e mussarela – rica em texturas",
    preco: "51.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, champignon, palmito, milho, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Calabresa Light",
    descricao: "Calabresa grelhada com cebola – mais leve",
    preco: "44.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa grelhada, cebola, mussarela light, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Pepperone",
    descricao: "Mussarela, pepperone, cebola e parmesão – sabor intenso",
    preco: "48.90",
    categoria: "Calabresa",
    ingredientesTexto: "Pepperone, mussarela, cebola, parmesão, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Toscana",
    descricao: "Mussarela, calabresa, cebola e parmesão – cremosa e forte",
    preco: "46.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, mussarela, cebola, parmesão, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Paulista",
    descricao: "Mussarela, calabresa, ovos e azeitonas – tradicional brasileira",
    preco: "45.90",
    categoria: "Calabresa",
    ingredientesTexto: "Calabresa, mussarela, ovos, azeitona, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },

  // LOMBO (5 pizzas)
  {
    nome: "Canadense",
    descricao: "Lombinho com catupiry – cremosa e suave",
    preco: "48.90",
    categoria: "Lombo",
    ingredientesTexto: "Lombo canadense, catupiry, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Cancun",
    descricao: "Lombinho, champignon, catupiry, bacon, tomate e parmesão – gourmet",
    preco: "55.90",
    categoria: "Lombo",
    ingredientesTexto: "Lombo, champignon, catupiry, bacon, tomate, parmesão, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 22,
  },
  {
    nome: "Italiana",
    descricao: "Lombinho, palmito, milho e catupiry – equilibrada",
    preco: "51.90",
    categoria: "Lombo",
    ingredientesTexto: "Lombo, palmito, milho, catupiry, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Palestra",
    descricao: "Lombo, brócolis, champignon e catupiry – rica em sabor",
    preco: "52.90",
    categoria: "Lombo",
    ingredientesTexto: "Lombo, brócolis, champignon, catupiry, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 21,
  },
  {
    nome: "Paris",
    descricao: "Lombo, tomate picado, champignon, cebola e mussarela – refinada",
    preco: "50.90",
    categoria: "Lombo",
    ingredientesTexto: "Lombo, tomate, champignon, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },

  // PRESUNTO (10 pizzas)
  {
    nome: "Portuguesa",
    descricao: "Mussarela, presunto, ervilha, ovos e cebola – clássica",
    preco: "46.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, mussarela, ervilha, ovos, cebola, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Portuga",
    descricao: "Presunto, palmito, cebola, ovo, bacon e mussarela",
    preco: "49.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, palmito, cebola, ovo, bacon, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Aurora",
    descricao: "Presunto, champignon, bacon, catupiry, tomate e parmesão",
    preco: "52.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, champignon, bacon, catupiry, tomate, parmesão, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 21,
  },
  {
    nome: "Amazon",
    descricao: "Presunto, brócolis, palmito, tomate e milho",
    preco: "48.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, brócolis, palmito, tomate, milho, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Moda da Casa",
    descricao: "Presunto, ovos, abobrinha, cebola e mussarela",
    preco: "47.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, ovos, abobrinha, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Veneza",
    descricao: "Presunto, palmito, milho, champignon e mussarela",
    preco: "50.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, palmito, milho, champignon, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Cubana",
    descricao: "Presunto, ovos, brócolis, tomate, cebola e mussarela",
    preco: "48.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, ovos, brócolis, tomate, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Grega",
    descricao: "Presunto, palmito, ovos, milho e catupiry",
    preco: "51.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, palmito, ovos, milho, catupiry, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Primavera",
    descricao: "Presunto, milho, palmito e mussarela",
    preco: "46.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, milho, palmito, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Baúru",
    descricao: "Presunto, tomate e mussarela",
    preco: "42.90",
    categoria: "Presunto",
    ingredientesTexto: "Presunto, tomate, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },

  // FRANGO (7 pizzas)
  {
    nome: "Frango com Catupiry",
    descricao: "Frango desfiado com catupiry",
    preco: "46.90",
    categoria: "Frango",
    ingredientesTexto: "Frango desfiado, catupiry, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Framily",
    descricao: "Frango, milho e mussarela",
    preco: "44.90",
    categoria: "Frango",
    ingredientesTexto: "Frango, milho, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Frangobom",
    descricao: "Frango, atum, brócolis e mussarela",
    preco: "49.90",
    categoria: "Frango",
    ingredientesTexto: "Frango, atum, brócolis, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Frango",
    descricao: "Frango, atum, champignon, brócolis, mussarela e catupiry",
    preco: "52.90",
    categoria: "Frango",
    ingredientesTexto: "Frango, atum, champignon, brócolis, mussarela, catupiry, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 21,
  },
  {
    nome: "Frangote",
    descricao: "Frango, milho, bacon e mussarela",
    preco: "48.90",
    categoria: "Frango",
    ingredientesTexto: "Frango, milho, bacon, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Moda Caipira",
    descricao: "Frango, milho, legumes, champignon e mussarela",
    preco: "50.90",
    categoria: "Frango",
    ingredientesTexto: "Frango, milho, cenoura, ervilha, champignon, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Frango Roquefão",
    descricao: "Frango com requeijão da casa",
    preco: "47.90",
    categoria: "Frango",
    ingredientesTexto: "Frango, requeijão, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },

  // PEITO DE PERU (4 pizzas)
  {
    nome: "Peru",
    descricao: "Peito de peru, tomate, cebola, azeitona e catupiry",
    preco: "48.90",
    categoria: "Peito de Peru",
    ingredientesTexto: "Peito de peru, tomate, cebola, azeitona, catupiry, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Cariú",
    descricao: "Peito de peru, cebola, champignon, milho e mussarela",
    preco: "50.90",
    categoria: "Peito de Peru",
    ingredientesTexto: "Peito de peru, cebola, champignon, milho, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Peruana",
    descricao: "Peito de peru, palmito, ovos e mussarela",
    preco: "49.90",
    categoria: "Peito de Peru",
    ingredientesTexto: "Peito de peru, palmito, ovos, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Florense",
    descricao: "Peito de peru, brócolis, champignon, milho e mussarela",
    preco: "51.90",
    categoria: "Peito de Peru",
    ingredientesTexto: "Peito de peru, brócolis, champignon, milho, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },

  // LEGUMES (4 pizzas)
  {
    nome: "Abobrinha",
    descricao: "Mussarela, abobrinha, cebola, parmesão e alho",
    preco: "43.90",
    categoria: "Legumes",
    ingredientesTexto: "Abobrinha, mussarela, cebola, parmesão, alho, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Abobrinha Bacon",
    descricao: "Mussarela, abobrinha, bacon e alho",
    preco: "46.90",
    categoria: "Legumes",
    ingredientesTexto: "Abobrinha, bacon, mussarela, alho, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Berinjela",
    descricao: "Mussarela, berinjela, cebola, parmesão e alho",
    preco: "44.90",
    categoria: "Legumes",
    ingredientesTexto: "Berinjela, mussarela, cebola, parmesão, alho, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Beijim",
    descricao: "Mussarela, berinjela, tomate, bacon e alho",
    preco: "47.90",
    categoria: "Legumes",
    ingredientesTexto: "Berinjela, tomate, bacon, mussarela, alho, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },

  // QUEIJOS (14 pizzas)
  {
    nome: "Mussarela",
    descricao: "Mussarela tradicional",
    preco: "38.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 15,
  },
  {
    nome: "Marguerita",
    descricao: "Mussarela, tomate, parmesão e manjericão",
    preco: "42.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, tomate, parmesão, manjericão, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Napolitana",
    descricao: "Mussarela, parmesão e tomate",
    preco: "41.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, parmesão, tomate, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 16,
  },
  {
    nome: "Dois Queijos",
    descricao: "Mussarela e requeijão",
    preco: "44.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, requeijão",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 16,
  },
  {
    nome: "Quatro Queijos",
    descricao: "Mussarela, provolone, requeijão e parmesão",
    preco: "52.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, provolone, requeijão, parmesão",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Cinco Queijos",
    descricao: "Mussarela, provolone, catupiry, parmesão e gorgonzola",
    preco: "58.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, provolone, catupiry, parmesão, gorgonzola",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Catupiry",
    descricao: "Catupiry puro",
    preco: "46.90",
    categoria: "Queijos",
    ingredientesTexto: "Catupiry, mussarela",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 16,
  },
  {
    nome: "Catupiry Bacon",
    descricao: "Catupiry com bacon",
    preco: "49.90",
    categoria: "Queijos",
    ingredientesTexto: "Catupiry, bacon, mussarela",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Catupiry Milho",
    descricao: "Catupiry com milho",
    preco: "47.90",
    categoria: "Queijos",
    ingredientesTexto: "Catupiry, milho, mussarela",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Siciliana",
    descricao: "Mussarela, champignon e bacon",
    preco: "48.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, champignon, bacon, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Espiga",
    descricao: "Milho, mussarela, catupiry e alho",
    preco: "45.90",
    categoria: "Queijos",
    ingredientesTexto: "Milho, mussarela, catupiry, alho",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 17,
  },
  {
    nome: "Mussarela de Búfala",
    descricao: "Mussarela de búfala, tomate seco e rúcula",
    preco: "62.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela de búfala, tomate seco, rúcula, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Francesa",
    descricao: "Mussarela de búfala, champignon, tomate seco e milho",
    preco: "64.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela de búfala, champignon, tomate seco, milho, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Bacon",
    descricao: "Mussarela, bacon e ovos",
    preco: "45.90",
    categoria: "Queijos",
    ingredientesTexto: "Mussarela, bacon, ovos, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },

  // VARIADAS (7 pizzas aqui - no cardápio original são 27, mas vou incluir as principais)
  {
    nome: "Alho",
    descricao: "Alho, mussarela, parmesão e tomate",
    preco: "40.90",
    categoria: "Variadas",
    ingredientesTexto: "Alho, mussarela, parmesão, tomate, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 16,
  },
  {
    nome: "Carne Seca",
    descricao: "Mussarela, carne seca e cebola",
    preco: "54.90",
    categoria: "Variadas",
    ingredientesTexto: "Carne seca, mussarela, cebola, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 20,
  },
  {
    nome: "Fiorentina",
    descricao: "Palmito, ervilha, bacon, cebola e mussarela",
    preco: "49.90",
    categoria: "Variadas",
    ingredientesTexto: "Palmito, ervilha, bacon, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Indiana",
    descricao: "Brócolis, alho, catupiry e parmesão",
    preco: "46.90",
    categoria: "Variadas",
    ingredientesTexto: "Brócolis, alho, catupiry, parmesão, mussarela",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Inglesa",
    descricao: "Frango, bacon, milho e ervilha",
    preco: "48.90",
    categoria: "Variadas",
    ingredientesTexto: "Frango, bacon, milho, ervilha, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },
  {
    nome: "Japonesa",
    descricao: "Escarola e champignon",
    preco: "43.90",
    categoria: "Variadas",
    ingredientesTexto: "Escarola, champignon, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 18,
  },
  {
    nome: "Mineira",
    descricao: "Mussarela, calabresa, palmito, milho e cebola",
    preco: "47.90",
    categoria: "Variadas",
    ingredientesTexto: "Calabresa, palmito, milho, cebola, mussarela, molho de tomate",
    tipoPizza: "salgada",
    tempoPreparoEstimado: 19,
  },

  // DOCES (7 pizzas)
  {
    nome: "Sensação",
    descricao: "Leite condensado, chocolate e morango",
    preco: "38.90",
    categoria: "Doces",
    ingredientesTexto: "Leite condensado, chocolate, morango",
    tipoPizza: "doce",
    tempoPreparoEstimado: 12,
  },
  {
    nome: "Romeu e Julieta",
    descricao: "Goiabada e mussarela",
    preco: "36.90",
    categoria: "Doces",
    ingredientesTexto: "Goiabada, mussarela",
    tipoPizza: "doce",
    tempoPreparoEstimado: 12,
  },
  {
    nome: "Brigadeiro",
    descricao: "Leite condensado, chocolate e granulado",
    preco: "35.90",
    categoria: "Doces",
    ingredientesTexto: "Leite condensado, chocolate, granulado",
    tipoPizza: "doce",
    tempoPreparoEstimado: 10,
  },
  {
    nome: "Chocolate",
    descricao: "Chocolate com castanha, nozes, granulado e cereja",
    preco: "42.90",
    categoria: "Doces",
    ingredientesTexto: "Chocolate, castanha, nozes, granulado, cereja",
    tipoPizza: "doce",
    tempoPreparoEstimado: 14,
  },
  {
    nome: "Banana Mussarela",
    descricao: "Mussarela, banana, canela, leite condensado e uva passa",
    preco: "37.90",
    categoria: "Doces",
    ingredientesTexto: "Mussarela, banana, canela, leite condensado, uva passa",
    tipoPizza: "doce",
    tempoPreparoEstimado: 13,
  },
  {
    nome: "Banana Chocolate",
    descricao: "Banana, canela, leite condensado e chocolate",
    preco: "39.90",
    categoria: "Doces",
    ingredientesTexto: "Banana, canela, leite condensado, chocolate",
    tipoPizza: "doce",
    tempoPreparoEstimado: 13,
  },
  {
    nome: "Banocolate",
    descricao: "Mussarela, banana, canela, leite condensado e chocolate",
    preco: "40.90",
    categoria: "Doces",
    ingredientesTexto: "Mussarela, banana, canela, leite condensado, chocolate",
    tipoPizza: "doce",
    tempoPreparoEstimado: 14,
  },
];

export async function popularCardapio(tenantId: string) {
  console.log(`🍕 Populando cardápio para tenant ${tenantId}...`);

  for (const pizza of cardapio) {
    try {
      await db.insert(produtos).values({
        tenantId,
        ...pizza,
      });
      console.log(`✅ ${pizza.nome} cadastrada`);
    } catch (error) {
      console.error(`❌ Erro ao cadastrar ${pizza.nome}:`, error);
    }
  }

  console.log(`\n🎉 Cardápio completo! ${cardapio.length} pizzas cadastradas.\n`);
}

// Se executado diretamente
if (require.main === module) {
  const tenantId = process.argv[2];
  if (!tenantId) {
    console.error("❌ Uso: ts-node server/scripts/popular-cardapio.ts <tenant-id>");
    process.exit(1);
  }
  popularCardapio(tenantId).then(() => process.exit(0));
}
